### ISSUE TITLE
Model Weights Unavailable

### ISSUE THREAD

**Issue by Abhishek-P** [kabrapratik28/DeepNews#24]
Hi Pratik, 

 I was trying to download and use the model weights but drive is giving 404 for the link.

**Comment by kabrapratik28** [comment]
Hi Abhishek -- I don't have the weights with me any more. There are new state of the art in this area and I will suggest trying those out -- BERT (https://huggingface.co/transformers/) and they have pre-trained model as well which you can fine tune on news dataset provided in this repository.

**Comment by Abhishek-P** [comment]
I was looking for a word2vec model to use for Devanagari word similarity. But, will try and find or build word2vec model for my use case, Thanks for the quick response.
